//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frmChucNang.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IQLKSKhoiDong")]
    public interface IQLKSKhoiDong {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLKSKhoiDong/Khoi_dong_dang_nhap", ReplyAction="http://tempuri.org/IQLKSKhoiDong/Khoi_dong_dang_nhapResponse")]
        int Khoi_dong_dang_nhap(string tk, string mk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLKSKhoiDong/Khoi_dong_dang_nhap", ReplyAction="http://tempuri.org/IQLKSKhoiDong/Khoi_dong_dang_nhapResponse")]
        System.Threading.Tasks.Task<int> Khoi_dong_dang_nhapAsync(string tk, string mk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLKSKhoiDong/Themloaiphong", ReplyAction="http://tempuri.org/IQLKSKhoiDong/ThemloaiphongResponse")]
        bool Themloaiphong(string loaiphong, float gia, int sotd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLKSKhoiDong/Themloaiphong", ReplyAction="http://tempuri.org/IQLKSKhoiDong/ThemloaiphongResponse")]
        System.Threading.Tasks.Task<bool> ThemloaiphongAsync(string loaiphong, float gia, int sotd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLKSKhoiDong/XoaLoaiPhong", ReplyAction="http://tempuri.org/IQLKSKhoiDong/XoaLoaiPhongResponse")]
        bool XoaLoaiPhong(string loaiphong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLKSKhoiDong/XoaLoaiPhong", ReplyAction="http://tempuri.org/IQLKSKhoiDong/XoaLoaiPhongResponse")]
        System.Threading.Tasks.Task<bool> XoaLoaiPhongAsync(string loaiphong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLKSKhoiDong/ThongTin_LoaiPhong", ReplyAction="http://tempuri.org/IQLKSKhoiDong/ThongTin_LoaiPhongResponse")]
        string ThongTin_LoaiPhong(string loaiphong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLKSKhoiDong/ThongTin_LoaiPhong", ReplyAction="http://tempuri.org/IQLKSKhoiDong/ThongTin_LoaiPhongResponse")]
        System.Threading.Tasks.Task<string> ThongTin_LoaiPhongAsync(string loaiphong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLKSKhoiDong/CapNhat_LoaiPhong", ReplyAction="http://tempuri.org/IQLKSKhoiDong/CapNhat_LoaiPhongResponse")]
        bool CapNhat_LoaiPhong(string old_loai_phong, string loai_phong, float don_gia, int so_nguoi_td, int sltrong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLKSKhoiDong/CapNhat_LoaiPhong", ReplyAction="http://tempuri.org/IQLKSKhoiDong/CapNhat_LoaiPhongResponse")]
        System.Threading.Tasks.Task<bool> CapNhat_LoaiPhongAsync(string old_loai_phong, string loai_phong, float don_gia, int so_nguoi_td, int sltrong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLKSKhoiDong/Load_DanhMucPhong", ReplyAction="http://tempuri.org/IQLKSKhoiDong/Load_DanhMucPhongResponse")]
        string Load_DanhMucPhong();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLKSKhoiDong/Load_DanhMucPhong", ReplyAction="http://tempuri.org/IQLKSKhoiDong/Load_DanhMucPhongResponse")]
        System.Threading.Tasks.Task<string> Load_DanhMucPhongAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLKSKhoiDong/ThemPhieuThue", ReplyAction="http://tempuri.org/IQLKSKhoiDong/ThemPhieuThueResponse")]
        bool ThemPhieuThue(string ten_kh, string cmnd, string sdt, string loaikh, string ma_phong, string tg_bd, string tg_kt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLKSKhoiDong/ThemPhieuThue", ReplyAction="http://tempuri.org/IQLKSKhoiDong/ThemPhieuThueResponse")]
        System.Threading.Tasks.Task<bool> ThemPhieuThueAsync(string ten_kh, string cmnd, string sdt, string loaikh, string ma_phong, string tg_bd, string tg_kt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLKSKhoiDong/LayThongTinPhieuThue", ReplyAction="http://tempuri.org/IQLKSKhoiDong/LayThongTinPhieuThueResponse")]
        string LayThongTinPhieuThue(string ma_phong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLKSKhoiDong/LayThongTinPhieuThue", ReplyAction="http://tempuri.org/IQLKSKhoiDong/LayThongTinPhieuThueResponse")]
        System.Threading.Tasks.Task<string> LayThongTinPhieuThueAsync(string ma_phong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLKSKhoiDong/Them_phong", ReplyAction="http://tempuri.org/IQLKSKhoiDong/Them_phongResponse")]
        bool Them_phong(string tk, string ma_phong, string loai_phong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLKSKhoiDong/Them_phong", ReplyAction="http://tempuri.org/IQLKSKhoiDong/Them_phongResponse")]
        System.Threading.Tasks.Task<bool> Them_phongAsync(string tk, string ma_phong, string loai_phong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLKSKhoiDong/Xoa_phong", ReplyAction="http://tempuri.org/IQLKSKhoiDong/Xoa_phongResponse")]
        bool Xoa_phong(string tk, string ma_phong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLKSKhoiDong/Xoa_phong", ReplyAction="http://tempuri.org/IQLKSKhoiDong/Xoa_phongResponse")]
        System.Threading.Tasks.Task<bool> Xoa_phongAsync(string tk, string ma_phong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLKSKhoiDong/Cap_nhap_phong", ReplyAction="http://tempuri.org/IQLKSKhoiDong/Cap_nhap_phongResponse")]
        bool Cap_nhap_phong(string old_ma_phong, string ma_phong, string loai_phong, string tinhtrang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLKSKhoiDong/Cap_nhap_phong", ReplyAction="http://tempuri.org/IQLKSKhoiDong/Cap_nhap_phongResponse")]
        System.Threading.Tasks.Task<bool> Cap_nhap_phongAsync(string old_ma_phong, string ma_phong, string loai_phong, string tinhtrang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLKSKhoiDong/Load_DsPhong", ReplyAction="http://tempuri.org/IQLKSKhoiDong/Load_DsPhongResponse")]
        string Load_DsPhong(string tk, string LoaiPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLKSKhoiDong/Load_DsPhong", ReplyAction="http://tempuri.org/IQLKSKhoiDong/Load_DsPhongResponse")]
        System.Threading.Tasks.Task<string> Load_DsPhongAsync(string tk, string LoaiPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLKSKhoiDong/LayThongTinDichVu", ReplyAction="http://tempuri.org/IQLKSKhoiDong/LayThongTinDichVuResponse")]
        string LayThongTinDichVu(string loai_phong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLKSKhoiDong/LayThongTinDichVu", ReplyAction="http://tempuri.org/IQLKSKhoiDong/LayThongTinDichVuResponse")]
        System.Threading.Tasks.Task<string> LayThongTinDichVuAsync(string loai_phong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLKSKhoiDong/ThemHoaDon", ReplyAction="http://tempuri.org/IQLKSKhoiDong/ThemHoaDonResponse")]
        bool ThemHoaDon(string maphieuthue, string maphong, string ngay_thanh_toan, float tongtien, string tk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLKSKhoiDong/ThemHoaDon", ReplyAction="http://tempuri.org/IQLKSKhoiDong/ThemHoaDonResponse")]
        System.Threading.Tasks.Task<bool> ThemHoaDonAsync(string maphieuthue, string maphong, string ngay_thanh_toan, float tongtien, string tk);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQLKSKhoiDongChannel : frmChucNang.ServiceReference1.IQLKSKhoiDong, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QLKSKhoiDongClient : System.ServiceModel.ClientBase<frmChucNang.ServiceReference1.IQLKSKhoiDong>, frmChucNang.ServiceReference1.IQLKSKhoiDong {
        
        public QLKSKhoiDongClient() {
        }
        
        public QLKSKhoiDongClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QLKSKhoiDongClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QLKSKhoiDongClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QLKSKhoiDongClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Khoi_dong_dang_nhap(string tk, string mk) {
            return base.Channel.Khoi_dong_dang_nhap(tk, mk);
        }
        
        public System.Threading.Tasks.Task<int> Khoi_dong_dang_nhapAsync(string tk, string mk) {
            return base.Channel.Khoi_dong_dang_nhapAsync(tk, mk);
        }
        
        public bool Themloaiphong(string loaiphong, float gia, int sotd) {
            return base.Channel.Themloaiphong(loaiphong, gia, sotd);
        }
        
        public System.Threading.Tasks.Task<bool> ThemloaiphongAsync(string loaiphong, float gia, int sotd) {
            return base.Channel.ThemloaiphongAsync(loaiphong, gia, sotd);
        }
        
        public bool XoaLoaiPhong(string loaiphong) {
            return base.Channel.XoaLoaiPhong(loaiphong);
        }
        
        public System.Threading.Tasks.Task<bool> XoaLoaiPhongAsync(string loaiphong) {
            return base.Channel.XoaLoaiPhongAsync(loaiphong);
        }
        
        public string ThongTin_LoaiPhong(string loaiphong) {
            return base.Channel.ThongTin_LoaiPhong(loaiphong);
        }
        
        public System.Threading.Tasks.Task<string> ThongTin_LoaiPhongAsync(string loaiphong) {
            return base.Channel.ThongTin_LoaiPhongAsync(loaiphong);
        }
        
        public bool CapNhat_LoaiPhong(string old_loai_phong, string loai_phong, float don_gia, int so_nguoi_td, int sltrong) {
            return base.Channel.CapNhat_LoaiPhong(old_loai_phong, loai_phong, don_gia, so_nguoi_td, sltrong);
        }
        
        public System.Threading.Tasks.Task<bool> CapNhat_LoaiPhongAsync(string old_loai_phong, string loai_phong, float don_gia, int so_nguoi_td, int sltrong) {
            return base.Channel.CapNhat_LoaiPhongAsync(old_loai_phong, loai_phong, don_gia, so_nguoi_td, sltrong);
        }
        
        public string Load_DanhMucPhong() {
            return base.Channel.Load_DanhMucPhong();
        }
        
        public System.Threading.Tasks.Task<string> Load_DanhMucPhongAsync() {
            return base.Channel.Load_DanhMucPhongAsync();
        }
        
        public bool ThemPhieuThue(string ten_kh, string cmnd, string sdt, string loaikh, string ma_phong, string tg_bd, string tg_kt) {
            return base.Channel.ThemPhieuThue(ten_kh, cmnd, sdt, loaikh, ma_phong, tg_bd, tg_kt);
        }
        
        public System.Threading.Tasks.Task<bool> ThemPhieuThueAsync(string ten_kh, string cmnd, string sdt, string loaikh, string ma_phong, string tg_bd, string tg_kt) {
            return base.Channel.ThemPhieuThueAsync(ten_kh, cmnd, sdt, loaikh, ma_phong, tg_bd, tg_kt);
        }
        
        public string LayThongTinPhieuThue(string ma_phong) {
            return base.Channel.LayThongTinPhieuThue(ma_phong);
        }
        
        public System.Threading.Tasks.Task<string> LayThongTinPhieuThueAsync(string ma_phong) {
            return base.Channel.LayThongTinPhieuThueAsync(ma_phong);
        }
        
        public bool Them_phong(string tk, string ma_phong, string loai_phong) {
            return base.Channel.Them_phong(tk, ma_phong, loai_phong);
        }
        
        public System.Threading.Tasks.Task<bool> Them_phongAsync(string tk, string ma_phong, string loai_phong) {
            return base.Channel.Them_phongAsync(tk, ma_phong, loai_phong);
        }
        
        public bool Xoa_phong(string tk, string ma_phong) {
            return base.Channel.Xoa_phong(tk, ma_phong);
        }
        
        public System.Threading.Tasks.Task<bool> Xoa_phongAsync(string tk, string ma_phong) {
            return base.Channel.Xoa_phongAsync(tk, ma_phong);
        }
        
        public bool Cap_nhap_phong(string old_ma_phong, string ma_phong, string loai_phong, string tinhtrang) {
            return base.Channel.Cap_nhap_phong(old_ma_phong, ma_phong, loai_phong, tinhtrang);
        }
        
        public System.Threading.Tasks.Task<bool> Cap_nhap_phongAsync(string old_ma_phong, string ma_phong, string loai_phong, string tinhtrang) {
            return base.Channel.Cap_nhap_phongAsync(old_ma_phong, ma_phong, loai_phong, tinhtrang);
        }
        
        public string Load_DsPhong(string tk, string LoaiPhong) {
            return base.Channel.Load_DsPhong(tk, LoaiPhong);
        }
        
        public System.Threading.Tasks.Task<string> Load_DsPhongAsync(string tk, string LoaiPhong) {
            return base.Channel.Load_DsPhongAsync(tk, LoaiPhong);
        }
        
        public string LayThongTinDichVu(string loai_phong) {
            return base.Channel.LayThongTinDichVu(loai_phong);
        }
        
        public System.Threading.Tasks.Task<string> LayThongTinDichVuAsync(string loai_phong) {
            return base.Channel.LayThongTinDichVuAsync(loai_phong);
        }
        
        public bool ThemHoaDon(string maphieuthue, string maphong, string ngay_thanh_toan, float tongtien, string tk) {
            return base.Channel.ThemHoaDon(maphieuthue, maphong, ngay_thanh_toan, tongtien, tk);
        }
        
        public System.Threading.Tasks.Task<bool> ThemHoaDonAsync(string maphieuthue, string maphong, string ngay_thanh_toan, float tongtien, string tk) {
            return base.Channel.ThemHoaDonAsync(maphieuthue, maphong, ngay_thanh_toan, tongtien, tk);
        }
    }
}
